apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault-bank-prod

resources:
  - prometheus-discovery-rbac.yaml
  - allow-prometheus-scrape.yaml
  - allow-shared-runtime-egress.yaml
  - shared-runtime-aliases.yaml
  - namespace.yaml
  - ../../base
  - runtime-serviceaccount.yaml
  - resource-quota.yaml

  - exposure/https-redirect-middleware.yaml
  - exposure/frontend-http-ingress.yaml
  - exposure/frontend-https-ingress.yaml
  - exposure/frontend-networkpolicy.yaml
  - exposure/api-http-ingress.yaml
  - exposure/api-https-ingress.yaml
  - exposure/backend-networkpolicies.yaml
images:
  - name: auth-service
    newName: harbor.vaultbank.internal:9443/vault-bank/auth-service
    digest: sha256:3afb1e69ac883a4f8b1fa9f6e1375a668e7b24a802de6212e045925b1253bf8c
  - name: account-service
    newName: harbor.vaultbank.internal:9443/vault-bank/account-service
    digest: sha256:015ff0bdfdf66b588c939a690f17e633d31b40a848d64380bddf1696312d7035
  - name: transaction-service
    newName: harbor.vaultbank.internal:9443/vault-bank/transaction-service
    digest: sha256:8bb2db08a1c506eca492df4dce24d422cb23074491f9be5b53f438ac74c8fece
  - name: payment-service
    newName: harbor.vaultbank.internal:9443/vault-bank/payment-service
    digest: sha256:bbf58024bc16087942d7423e7d4a856270610f7ae34e082cd31aeee0a35ef4d9
  - name: notification-service
    newName: harbor.vaultbank.internal:9443/vault-bank/notification-service
    digest: sha256:e5e28de08c3636275aa56beea25f347d868171cdade600a9ff9b580327d1a449
  - name: frontend
    newName: harbor.vaultbank.internal:9443/vault-bank/frontend
    digest: sha256:2193523731f9c93501b9d64a8eec35d430ed44bb6df5319b90e43d4aef192413

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=vaultbank
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "3"
      - op: add
        path: /spec/template/metadata/annotations
        value:
          vault-bank.io/staging-health-refresh: "2026-08-08T000000Z"
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: vault-bank-runtime
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: add
        path: /spec/strategy
        value:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1

  - target:
      version: v1
      kind: ConfigMap
      name: banking-runtime-config
    patch: |-
      - op: replace
        path: /data/DATABASE_SSL
        value: "false"
